Fix/109 printing issues
railslove/rcvr-app pull request #238
Opened 2021-06-16 09:04 UTC by ThorDro

2021-06-16 12:49 UTC, salimhb requested changes

2021-06-16 12:49 UTC, salimhb commented on pages/business/setup/keys.tsx
> +  const css_inl = '@media print { .no-print{ display: none !important;} }'
Although I'm personally not a fan of it, but we're using [Styled Components](https://emotion.sh/docs/styled)
So CSS is not done like this inline, but using the `styled(...)` function. Example here: https://github.com/railslove/rcvr-app/blob/master/pages/business/setup/verify-key.tsx#L144-L149

2021-06-21 13:54 UTC, salimhb approved these changes

2021-08-17 07:31 UTC, stringparser approved these changes

2021-08-17 09:04 UTC, merged