Bring in the menu also on mobile
railslove/rcvr-app pull request #46
Opened 2020-10-19 10:22 UTC by stephanpavlovic

We were hiding the sidebar menu before, which results in mobile users can not pay :) 

<img width="356" alt="Bildschirmfoto 2020-10-19 um 12 14 56" src="https://user-images.githubusercontent.com/74421/96434571-c4c03780-1205-11eb-9cb7-574cce1c89c2.png">

2020-10-19 10:45 UTC, timomeh requested changes
![Screenshot_20201019-123943](https://user-images.githubusercontent.com/4227520/96440392-326d6300-1208-11eb-92f3-a482b1bf89fe.png)

This doesn't look right.

It was an intentional decision to hide the Sidebar navigation on mobile. Instead the user can navigate to the different screens with links on the overview screens. That's why everything is linked two times: in the navigation and inside the main area.

I would appreciate if we follow this and simply add a link to the profile on the user's overview page (where the companies are listed). Then the design won't break.

2020-10-19 11:01 UTC, stephanpavlovic commented
> ![Screenshot_20201019-123943](https://user-images.githubusercontent.com/4227520/96440392-326d6300-1208-11eb-92f3-a482b1bf89fe.png)
> 
> This doesn't look right.
> 
> It was an intentional decision to hide the Sidebar navigation on mobile. Instead the user can navigate to the different screens with links on the overview screens. That's why everything is linked two times: in the navigation and inside the main area.
> 
> I would appreciate if we follow this and simply add a link to the profile on the user's overview page (where the companies are listed). Then the design won't break.

I will then just add a link to both content areas (profile and also company page) because with the decision to hide the menu on mobile there is at the moment no chance for a user to get to the other, which is pretty bad mobile ux and results in a lot of customer calls for Max.

2020-10-19 11:06 UTC, timomeh commented
> because with the decision to hide the menu on mobile there is at the moment no chance for a user to get to the other

That's not true. There's a back link on each screen below the headline - only visible on mobile - so you can navigate back to the company overview or user overview. That's why it exists.

2020-10-20 14:11 UTC, salimhb approved these changes

2020-10-20 14:20 UTC, timomeh approved these changes

2020-10-20 14:35 UTC, merged