Signin with checkbox
railslove/rcvr-app pull request #50
Opened 2020-11-09 08:35 UTC by P3nny

Fixes: https://github.com/railslove/recover-backlog/issues/2

We're choosing an explicit variant of linking to the contract.

2020-11-09 08:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/railslove/rcvr-app?pullRequest=50) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/railslove/rcvr-app?pullRequest=50) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/railslove/rcvr-app?pullRequest=50) it.</sub>

2020-11-10 08:42 UTC, P3nny commented
Please delete the contract.pdf and move the link to the word "Nutzungsvertrag"

2020-11-17 15:32 UTC, salimhb requested changes

2020-11-17 15:32 UTC, salimhb commented on pages/business/setup/signup.tsx
> +  ),
This is blocking users who are not part of `isCareEnv` or `isHealthEnv` from registering as they don't have the `Checkbox` to confirm.

2020-11-17 15:37 UTC, salimhb requested changes

2020-11-17 15:37 UTC, salimhb commented on pages/business/setup/signup.tsx
> +          confirmContract: false,
```suggestion
          confirmContract: !isCareEnv && !isHealthEnv,
```
This should allow other users to register

2020-11-18 17:35 UTC, salimhb approved these changes
![](https://media2.giphy.com/media/30pjt9I0SDs7R4ghlp/giphy.gif)

2020-11-18 21:27 UTC, merged